### ISSUE TITLE
Could you share generated answers by OpenAI models?

### ISSUE THREAD

**Issue by jihyukkim-nlp** [princeton-nlp/ALCE#10]
Hi all, I am Jihyuk, a PhD student interested in factuality/verification for long-form QA.
I appreciate the open-sourcing of codes and data!

**I am wondering if the answers generated by OpenAI models can also be shared.**

I would like to conduct further analyses using actual samples from OpenAI models.
However, I would like to avoid expensive API calls to obtain the same results as presented in the paper.

Best regards,
Jihyuk

**Comment by gaotianyu1350** [comment]
Hi Jihyuk,

Sorry for the late reply. You can find all OpenAI model generated results here: 

https://drive.google.com/file/d/1cONFQbvANi-9mBCSBuLveS5cK8zko873/view?usp=sharing

**Comment by jihyukkim-nlp** [comment]
Thank you so much for sharing!

**Comment by jihyukkim-nlp** [comment]
Thank you so much for sharing!
