### ISSUE TITLE
How to install torch==2.1.0.dev20230514+cu118

### ISSUE THREAD

**Issue by BeastyZ** [princeton-nlp/ALCE#15]
I checked this website https://[download.pytorch.org/whl/nightly/torch/](https://download.pytorch.org/whl/nightly/torch/), there is no torch==2.1.0.dev20230514+cu118. So I downloaded another version, which is torch-2.1.0.dev20230706+cu121-cp39-cp39-linux_x86_64.whl. I used "pip install torch-2.1.0.dev20230706+cu121-cp39-cp39-linux_x86_64.whl" to install it, but got an error: 
ERROR: Could not find a version that satisfies the requirement pytorch-triton==2.1.0+440fd1bf20 (from torch) (from versions: 0.0.1)
ERROR: No matching distribution found for pytorch-triton==2.1.0+440fd1bf20

**Comment by gaotianyu1350** [comment]
Hi,

You can also just install the stable version of the latest pytorch (I believe it is 2.0.1). I don't think they will make a difference for our repo.

**Comment by BeastyZ** [comment]
I've found the solution, thanks.
