### ISSUE TITLE
A error occurred when evaluating

### ISSUE THREAD

**Issue by BeastyZ** [princeton-nlp/ALCE#16]
The error is like this:
File "/root/anaconda3/envs/alce/lib/python3.9/site-packages/numpy/core/memmap.py", line 268, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
ValueError: mmap length is greater than file size

**Comment by gaotianyu1350** [comment]
Hi,

Can you provide more stack error messages (so that we can see which line of code in our repo caused the error)?

**Comment by BeastyZ** [comment]
I've fixed this bug, thanks.
