### ISSUE TITLE
How to get top-100 GTR retrieved results for ASQA and QAMPARI

### ISSUE THREAD

**Issue by BeastyZ** [princeton-nlp/ALCE#17]
Hi, there is no question in the file of psgs_w100.tsv. How to get top-100 GTR retrieved results like asqa_eval_gtr_top100.json and qampari_eval_gtr_top100.json? By the way, how do you tell ASQA and QAMPARI using same corpus?

**Comment by gaotianyu1350** [comment]
Hi,

Sorry I didn't get the question. We provided the top-100 GTR results for ASQA and QAMPARI. Can you specify?

**Comment by BeastyZ** [comment]
Through reading your paper, I maybe find the answer. Thanks.
