### ISSUE TITLE
Evaluation Metrics about ASQA

### ISSUE THREAD

**Issue by sunhaopku** [princeton-nlp/ALCE#19]
Thanks for the author's open-source code. Most of the experimental results are reproducible. I just want to confirm that whether the EM score of ASQA is derived from the compute_str_em function or from the compute_qa function considering both have EM score output.

**Comment by gaotianyu1350** [comment]
Hi,

The EM scores reported in the paper correspond to "compute_str_em".

**Comment by sunhaopku** [comment]
Thanks for the reply
