### ISSUE TITLE
The human evaluation results

### ISSUE THREAD

**Issue by HuuuNan** [princeton-nlp/ALCE#20]
Hi there, 
The work is great and thank you for your code sharing. 
Would you share the human evaluation results in the Sec.6 and the script for "_evaluate the accuracy of your automatic metrics by treating the human annotations as gold labels._"? 
Thanks a lot.

**Comment by HuuuNan** [comment]
@gaotianyu1350 Thanks for your reply and update. Could you please also share the script for "_evaluate the accuracy of your automatic metrics by treating the human annotations as gold labels_", i.e. calculate the citation recall, citation precision, insufficient citations and irrelevant citations metrics? That would be helpful for understanding your work correctly.

**Comment by gaotianyu1350** [comment]
@howard-yen can you help sharing the script? Thanks!

**Comment by howard-yen** [comment]
Hi @HuuuNan, I updated the human_eval dir with the script, thanks for your interest in our project!
