### ISSUE TITLE
Retrieval implementation

### ISSUE THREAD

**Issue by HCY123902** [princeton-nlp/ALCE#5]
Hello, can I ask for the corpus and script that you used for the passage retrieval step? This does not seem to have been released here

**Comment by howard-yen** [comment]
Hi, we are working on releasing the retrieval code in the next few days :) 
As for the corpus, you can obtain the Wikipedia corpus from the DPR [repo](https://github.com/facebookresearch/DPR) and the Common Crawl corpus from the Spheres [repo](https://github.com/facebookresearch/Sphere).

**Comment by gaotianyu1350** [comment]
Hi, we just updated the code/readme and added the retrieval component!

**Comment by HCY123902** [comment]
Thank you for releasing this
